const INITIALIZE_DB = 'INITIALIZE_DB';
const INITIALIZE_BLOG = 'INITIALIZE_BLOG';

const initializeDB = ({
  FIREBASE_API_KEY = '',
  FIREBASE_AUTH_DOMAIN = '',
  FIREBASE_DATABASE_URL = '',
  FIREBASE_PROJECT_ID = '',
  FIREBASE_STORAGE_BUCKET = '',
  FIREBASE_MESSAGING_SENDER_ID = ''
} = {}) => ({
  type: INITIALIZE_DB,
  payload: {
    FIREBASE_API_KEY,
    FIREBASE_AUTH_DOMAIN,
    FIREBASE_DATABASE_URL,
    FIREBASE_PROJECT_ID,
    FIREBASE_STORAGE_BUCKET,
    FIREBASE_MESSAGING_SENDER_ID
  }
});

const initializeBlog = ({
  BLOGGER_API_KEY = ''
} = {}) => ({
  type: INITIALIZE_BLOG,
  payload: {
    BLOGGER_API_KEY
  }
});

export {
  INITIALIZE_DB,
  INITIALIZE_BLOG,
  initializeDB,
  initializeBlog
}
